#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>
#include "CryptoContext.hpp"

#include <algorithm>
#include <string>
#include <vector>

TEST_CASE("wrap then unwrap recovers the secret key") {
    CryptoContext cx;
    KeyPair kp = cx.generate_keypair();
    Kek kek;
    kek.fill(0x11);

    WrappedKey w = cx.wrap_key(kp.secret_key, kek);
    SecretKey out = cx.unwrap_key(w, kek);
    CHECK(out == kp.secret_key);
}

TEST_CASE("unwrap with a different key throws") {
    CryptoContext cx;
    KeyPair kp = cx.generate_keypair();
    Kek kek1;
    kek1.fill(0x11);
    Kek kek2;
    kek2.fill(0x22);

    WrappedKey w = cx.wrap_key(kp.secret_key, kek1);
    CHECK_THROWS_AS(cx.unwrap_key(w, kek2), CryptoError);
}

TEST_CASE("tampered ciphertext is rejected") {
    CryptoContext cx;
    KeyPair kp = cx.generate_keypair();
    Kek kek;
    kek.fill(0x11);

    WrappedKey w = cx.wrap_key(kp.secret_key, kek);
    w.ciphertext[0] ^= 0x01;
    CHECK_THROWS_AS(cx.unwrap_key(w, kek), CryptoError);
}

TEST_CASE("tampered nonce is rejected") {
    CryptoContext cx;
    KeyPair kp = cx.generate_keypair();
    Kek kek;
    kek.fill(0x11);

    WrappedKey w = cx.wrap_key(kp.secret_key, kek);
    w.nonce[0] ^= 0x01;
    CHECK_THROWS_AS(cx.unwrap_key(w, kek), CryptoError);
}

TEST_CASE("derive_kek is deterministic and a wrong password fails to unwrap") {
    CryptoContext cx;
    Salt salt = cx.random_salt();

    Kek a = cx.derive_kek("correct horse battery staple", salt);
    Kek b = cx.derive_kek("correct horse battery staple", salt);
    CHECK(a == b);   // same password + salt -> same kek

    KeyPair kp = cx.generate_keypair();
    WrappedKey w = cx.wrap_key(kp.secret_key, a);

    Kek wrong = cx.derive_kek("wrong password", salt);
    CHECK(wrong != a);
    CHECK_THROWS_AS(cx.unwrap_key(w, wrong), CryptoError);
}

TEST_CASE("two generated keypairs differ") {
    CryptoContext cx;
    KeyPair a = cx.generate_keypair();
    KeyPair b = cx.generate_keypair();
    CHECK(a.public_key != b.public_key);
    CHECK(a.secret_key != b.secret_key);
}

TEST_CASE("HPKE auth round-trips alice -> bob") {
    CryptoContext cx;
    KeyPair alice = cx.generate_keypair();   // sender
    KeyPair bob   = cx.generate_keypair();   // recipient
    std::vector<unsigned char> pt = {'h', 'e', 'l', 'l', 'o'};
    const std::string info = "eternal-blue-msg-v1";
    const std::string aad  = "alice|bob|123";

    Sealed s = cx.seal_auth(bob.public_key, alice.secret_key, info, aad, pt);
    auto out = cx.open_auth(s.enc, bob.secret_key, alice.public_key, info, aad, s.ciphertext);
    CHECK(out == pt);
}

TEST_CASE("HPKE auth interops with pyhpke (RFC 9180 known-answer vector)") {
    // generated by pyhpke 0.6.4 (a vetted RFC 9180 impl) for our exact suite,
    // mode_auth. if our open_auth recovers the plaintext, we are RFC-correct.
    auto from_hex = [](std::string_view h) {
        std::vector<unsigned char> b(h.size() / 2);
        for (size_t i = 0; i < b.size(); ++i)
            b[i] = static_cast<unsigned char>(std::stoi(std::string(h.substr(i * 2, 2)), nullptr, 16));
        return b;
    };
    auto to32 = [&](std::string_view h) {
        std::array<unsigned char, 32> a{};
        auto v = from_hex(h);
        std::copy(v.begin(), v.end(), a.begin());
        return a;
    };

    SecretKey skR = to32("688985041cbc8bbb7f2049cc126d82657a2e733a873e9b89de677d8b91b90a5e");
    PublicKey pkS = to32("25e84d456149f765b8dc02896bd355dafc037abcbf48d91962605045a7457d67");
    PublicKey enc = to32("be497ab495607cadf1bf7465fc0fd96cd509cb78fa0c36df93b7bf7877963c19");
    std::vector<unsigned char> ct =
        from_hex("b293adc154996de4716d95ba86cfad74a6ad370baaa5363793c7074e686917d27e4a53");

    CryptoContext cx;
    auto pt = cx.open_auth(enc, skR, pkS, "eternal-blue-msg-v1", "alice|bob|1716300000000", ct);
    CHECK(std::string(pt.begin(), pt.end()) == "the quick brown fox");
}

TEST_CASE("HPKE auth rejects tamper, wrong sender, wrong aad, wrong recipient") {
    CryptoContext cx;
    KeyPair alice = cx.generate_keypair();
    KeyPair bob   = cx.generate_keypair();
    KeyPair eve   = cx.generate_keypair();
    std::vector<unsigned char> pt = {'s', 'e', 'c', 'r', 'e', 't'};
    const std::string info = "eternal-blue-msg-v1";
    const std::string aad  = "alice|bob|123";

    Sealed s = cx.seal_auth(bob.public_key, alice.secret_key, info, aad, pt);

    SUBCASE("tampered ciphertext") {
        auto ct = s.ciphertext; ct[0] ^= 0x01;
        CHECK_THROWS_AS(cx.open_auth(s.enc, bob.secret_key, alice.public_key, info, aad, ct), CryptoError);
    }
    SUBCASE("wrong sender key") {
        CHECK_THROWS_AS(cx.open_auth(s.enc, bob.secret_key, eve.public_key, info, aad, s.ciphertext), CryptoError);
    }
    SUBCASE("wrong aad") {
        CHECK_THROWS_AS(cx.open_auth(s.enc, bob.secret_key, alice.public_key, info, "alice|bob|999", s.ciphertext), CryptoError);
    }
    SUBCASE("wrong recipient key") {
        CHECK_THROWS_AS(cx.open_auth(s.enc, eve.secret_key, alice.public_key, info, aad, s.ciphertext), CryptoError);
    }
}
